In this notebook we demonstrate the calculations related to the four fundamental subspaces 

In [1]:
import numpy as np

A = matrix([[1, 2, 2, 9, -1], 
            [1, 2, 3, 13, -2], 
            [-1, -2, -1, -5, 1], 
            [1, 2, 0, 1, 2]])

show(A)

[ 1  2  2  9 -1]
[ 1  2  3 13 -2]
[-1 -2 -1 -5  1]
[ 1  2  0  1  2]

The above matrix $A \: \in \: \mathbb{R}^{4X5}$ is selected for this demonstration. 

This matrix is also featured in the NPTEL video of Prof Vittal Rao

In [2]:
A.add_multiple_of_row(1, 0, -1) 
show(A)

[ 1  2  2  9 -1]
[ 0  0  1  4 -1]
[-1 -2 -1 -5  1]
[ 1  2  0  1  2]

In [3]:
A.add_multiple_of_row(2, 0, 1)
show(A)

[ 1  2  2  9 -1]
[ 0  0  1  4 -1]
[ 0  0  1  4  0]
[ 1  2  0  1  2]

In [4]:
A.add_multiple_of_row(3, 0, -1)
show(A)

[ 1  2  2  9 -1]
[ 0  0  1  4 -1]
[ 0  0  1  4  0]
[ 0  0 -2 -8  3]

At this stage we have cleaned up the first two columns as required

In [5]:
A.add_multiple_of_row(2, 1, -1)
show(A)

[ 1  2  2  9 -1]
[ 0  0  1  4 -1]
[ 0  0  0  0  1]
[ 0  0 -2 -8  3]

In [6]:
A.add_multiple_of_row(3, 1, 2)
show(A)

[ 1  2  2  9 -1]
[ 0  0  1  4 -1]
[ 0  0  0  0  1]
[ 0  0  0  0  1]

In [7]:
A.add_multiple_of_row(0, 1, -2)
show(A)

[ 1  2  0  1  1]
[ 0  0  1  4 -1]
[ 0  0  0  0  1]
[ 0  0  0  0  1]

In [8]:
A.add_multiple_of_row(3, 2, -1)
show(A)

[ 1  2  0  1  1]
[ 0  0  1  4 -1]
[ 0  0  0  0  1]
[ 0  0  0  0  0]

In [9]:
A.add_multiple_of_row(1, 2, 1)
show(A)

[1 2 0 1 1]
[0 0 1 4 0]
[0 0 0 0 1]
[0 0 0 0 0]

In [10]:
A.add_multiple_of_row(0, 2, -1)
show(A)

[1 2 0 1 0]
[0 0 1 4 0]
[0 0 0 0 1]
[0 0 0 0 0]

The above for is the row reduced echleon form of the matrix. There is also a direct command available in sagemath for obtaining the row reduced echleon form. I suggest do not use the command for calculation, use it only for verification. This will be important for your learning.  

It is evident that the dimension of the row space is 3. A basis for the row space is 
given by 

(1, 2, 0, 1, 0), (0, 0, 1, 4, 0) and (0, 0, 0, 0, 1) 

For finding the nullspace note the above equations read as follows: - 

$ x_1 + 2 x_2 + x_4 = 0 $

$ x_3 + 4 x_4 = 0 $

$ x_5 = 0 $

Alternatively, $x_2$ and $x_4$ (the non-pivot variables) can be chosen arbitrarily and the remaining variables viz. $x_1, x_3$ and $x_5$ (the pivot variables) are constrained by the above equations. 

Thus assuming $x_2 = \alpha $ and $x_4 = \beta$ we have 

$(-2 \alpha -\beta, \alpha, -4 \beta, \beta, 0) = \alpha(-2, 1, 0, 0, 0) + \beta (-1, 0, -4, 1, 0)$

Thus, the basis for the null space is given by 

(-2, 1, 0, 0, 0) and (-1, 0, -4, 1, 0)

Note the five dimensional input space $\mathbb{R}^5$ is decomposed into (i) a two dimensional null space and (ii) a three dimensional row space 

let us verify the orthogonality of the row space and the null space 

In [11]:
r1 = vector([1, 2, 0, 1, 0])

r2 = vector([0, 0, 1, 4, 0])

r3 = vector([0, 0, 0, 0, 1])

# the above are the basis of the row space 

n1 = vector([-2, 1, 0, 0, 0])

n2 = vector([-1, 0, -4, 1, 0])

# the above are the basis for the null space

In [13]:
show(r1.inner_product(n1))
show(r2.inner_product(n1))
show(r3.inner_product(n1))

show(r1.inner_product(n2))
show(r2.inner_product(n2))
show(r3.inner_product(n2))

0

0

0

0

0

0

Thus we see that row space and null space are orthogonal complements of each other

## Homework

Using the transpose of the matrix (or column operations available in Sagemath) perform the same decomposition in the 4 dimensional output space. In particular prove that column space is three dimensional, null space of transpose(A) is one dimensional and these two are orthogonal. 

In [6]:
A = matrix([[1, 2, 2, 9, -1], 
            [1, 2, 3, 13, -2], 
            [-1, -2, -1, -5, 1], 
            [1, 2, 0, 1, 2]])

show(A)

[ 1  2  2  9 -1]
[ 1  2  3 13 -2]
[-1 -2 -1 -5  1]
[ 1  2  0  1  2]

In [7]:
A = A.T
show(A)

[ 1  1 -1  1]
[ 2  2 -2  2]
[ 2  3 -1  0]
[ 9 13 -5  1]
[-1 -2  1  2]

In [8]:
A.add_multiple_of_row(1,0,-2)
A.add_multiple_of_row(2,0,-2)
A.add_multiple_of_row(3,0,-9)
A.add_multiple_of_row(4,0,1)
show(A)

[ 1  1 -1  1]
[ 0  0  0  0]
[ 0  1  1 -2]
[ 0  4  4 -8]
[ 0 -1  0  3]

In [9]:
A.add_multiple_of_row(3,2,-4)
A.add_multiple_of_row(4,2,1)
A.add_multiple_of_row(0,2,-1)
show(A)

[ 1  0 -2  3]
[ 0  0  0  0]
[ 0  1  1 -2]
[ 0  0  0  0]
[ 0  0  1  1]

In [10]:
A.add_multiple_of_row(2,4,-1)
A.add_multiple_of_row(0,4,2)
show(A)

[ 1  0  0  5]
[ 0  0  0  0]
[ 0  1  0 -3]
[ 0  0  0  0]
[ 0  0  1  1]

In [11]:
A.swap_rows(1,2)
A.swap_rows(2,4)
show(A)

[ 1  0  0  5]
[ 0  1  0 -3]
[ 0  0  1  1]
[ 0  0  0  0]
[ 0  0  0  0]